/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul2.lab6;


import java.awt.GridLayout;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import static javafx.scene.control.ButtonType.CLOSE;
import javax.swing.JLabel;
import javax.swing.JTable;
/**
 *
 * @author Acer
 */
public class PrintJFrame extends javax.swing.JFrame {

     private JTable tableToPrint;

    public PrintJFrame(JTable table) {
        initComponents();
        this.tableToPrint = table;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPrintReport = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPrintReport.setText("Print Report");
        jButtonPrintReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintReportActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(204, 255, 0));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButtonPrintReport))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButtonPrintReport)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void ggg(){
        jTable1.setModel(tableToPrint.getModel());
        /*jPanelReport.removeAll();
        jPanelReport.setLayout(new GridLayout(tableToPrint.getRowCount() + 1, tableToPrint.getColumnCount()));

        // Add table headers
        for (int i = 0; i < tableToPrint.getColumnCount(); i++) {
            JLabel headerLabel = new JLabel(tableToPrint.getColumnName(i));
            headerLabel.setHorizontalAlignment(JLabel.CENTER);
            jPanelReport.add(headerLabel);
        }

        // Add table data
        for (int i = 0; i < tableToPrint.getRowCount(); i++) {
            for (int j = 0; j < tableToPrint.getColumnCount(); j++) {
                JLabel dataLabel = new JLabel(String.valueOf(tableToPrint.getValueAt(i, j)));
                dataLabel.setHorizontalAlignment(JLabel.CENTER);
                jPanelReport.add(dataLabel);
            }
        }

        // Repaint panel
        jPanelReport.revalidate();
        jPanelReport.repaint();*/
    }
    private void jButtonPrintReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintReportActionPerformed
        try {
            // Create a printer job
            PrinterJob printerJob = PrinterJob.getPrinterJob();
            // Set the printable object
            printerJob.setPrintable(tableToPrint.getPrintable(javax.swing.JTable.PrintMode.NORMAL, null, null));
            // Display print dialog
            if (printerJob.printDialog()) {
                // If the user clicked OK to print, then print
                printerJob.print();
            }
        } catch (PrinterException ex) {
            ex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrintReportActionPerformed

    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PrintJFrame(tableToPrint).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrintReport;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
