/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul2.lab10;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Acer
 */
public class ProductJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProductJInternalFrame
     */
    private int Id;
    public ProductJInternalFrame() {
        Id=-1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        InsertButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Товар");

        jLabel2.setText("Наименование");

        InsertButton.setText("Добавить");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Изменить");
        UpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateButtonMouseClicked(evt);
            }
        });

        DeleteButton.setText("Удалить");
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeleteButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertButton)
                    .addComponent(UpdateButton)
                    .addComponent(DeleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Заполнение таблицы 
    private void FillTable() {
        try { 
            ResultSet resultSet;
            resultSet = StockSystem.unitOfWork.Products.GetAll();
            jTable2.setModel(DbUtils.resultSetToTableModel(resultSet));
        }catch(SQLException ex){
            Logger.getLogger(ProductJInternalFrame.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "Ошибка");
        }
    } // Получение записей из бд jTable1.setModel(DbUtils.resultSetToTableModel(resultSet)); // Присваивание таблице модели для заполнения } catch (SQLException ex) { Logger.getLogger(ProductJInternalFrame.class.getName()).log(Level.SEVERE, null, ex); JOptionPane.showMessageDialog(null, "○шибка"); } }

    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        FillTable();
    }//GEN-LAST:event_formInternalFrameOpened

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
if ( jTextField1.getText ( ) . length ( ) < 1 ){
       JOptionPane.showMessageDialog ( null , " Введите наименование товара ! " ) ;} // Вывод сообщения об ошибке
else 
    try {
        Product product = new Product();
        product.Name = jTextField1.getText();
        StockSystem.unitOfWork.Products.Create (product) ;
        jTextField1.setText("");

        JOptionPane.showMessageDialog ( null , " Добавлено " ) ;
        FillTable ( ) ;
    } catch ( SQLException ex ) {
        // Создание нового товара
        // Присваивание товару введенное наименование
        // Запрос на добавление записи в БД
        // Очищение поля
        // Вывод сообщения
        // Заполнение таблицы
        Logger.getLogger(ProductJInternalFrame.class.getName()).log (Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog ( null , " Ошибка " ) ;
    }                                                                                        
    }
    private void UpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateButtonMouseClicked
         if(Id<0) JOptionPane.showMessageDialog(null, "выберите запись в таблице для изменения");
        else if(jTextField1.getText().length()<1) JOptionPane.showMessageDialog(null, "Введите новое наименование товара");
        else
            try {
        Product product = new Product();
        product.Id = Id;
        product.Name = jTextField1.getText();
        StockSystem.unitOfWork.Products.Update(product) ;
                jTextField1.setText("");

        JOptionPane.showMessageDialog ( null , " Изменено " ) ;
        FillTable ( ) ;
    } catch ( SQLException ex ) {
        Logger.getLogger(ProductJInternalFrame.class.getName()).log (Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog ( null , " Ошибка " ) ;
    } // TODO add your handling code here: // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButtonMouseClicked

    private void DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseClicked
        if(Id<0) JOptionPane.showMessageDialog(null, "выберите запись в таблице для изменения");
        else
            try {
        StockSystem.unitOfWork.Products.Delete(Id) ;
           jTextField1.setText("");

        JOptionPane.showMessageDialog ( null , " Удалено " ) ;
        FillTable();
    } catch ( SQLException ex ) {
        Logger.getLogger(ProductJInternalFrame.class.getName()).log (Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog ( null , " Ошибка " ) ;
    } 
    }//GEN-LAST:event_DeleteButtonMouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        Id=(int)jTable2.getValueAt(jTable2.getSelectedRow(), 0);
        jTextField1.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton InsertButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
